set nocompatible
set backspace=
set ambiwidth=double "single: listchars, fillchars
set ttyfast
set tabstop=4
set shiftwidth=4
set textwidth=0
set expandtab
set autoindent
set smartindent
set breakindent
set cindent
set cinoptions=+2,t0,l1,j1,J1 "(s,L0
set formatoptions=tcroqnblmM1j
set cmdheight=1
set scrolloff=2
set laststatus=2
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,iso-2022-jp,euc-jp,sjis,default,latin1
set fileformat=unix
set fileformats=unix,dos,mac
set matchpairs=(:),{:},[:],<:>,=:;
set listchars=trail:.,extends:»,precedes:«
set fillchars=vert:¦,fold:\  "'vert:\│,fold:─
set list
set hlsearch
set incsearch
set smartcase
set noswapfile
set nobackup
set noshowmode
set clipboard=unnamedplus
set conceallevel=0
"set lazyredraw "disable for fix lightline
set wildmenu
set number
set wrap
set nofoldenable
set mouse=nv
set timeoutlen=10
set nocursorline "fix for slow scrolling
set background=dark
let g:skip_defaults_vim=1 "disable defaults.vim
let g:html_indent_style1='inc' "fix style tag indent
let g:html_indent_script1='inc' "fix script tag indent
noremap <silent> q <nop>
noremap <silent> <s-q> <nop>
nnoremap <silent> <tab> <c-w>w
nnoremap <silent> <s-tab> <c-w>W
filetype plugin indent on
highlight vertsplit cterm=none ctermfg=darkgray ctermbg=none
"highlight linenr cterm=none ctermfg=darkgray ctermbg=none
"highlight cursorline cterm=none ctermfg=none ctermbg=none
"highlight cursorlinenr cterm=none ctermfg=white ctermbg=none
"autocmd filetype * setlocal formatoptions=tcroqnblmM1j
autocmd BufEnter * if &filetype == '' | setlocal filetype=text | endif
autocmd InsertLeave * call system('fcitx-remote -c')
autocmd VimLeave * call system('xsel -ib', getreg('+'))
autocmd ColorScheme * call onedark#set_highlight('normal',{'fg':{'gui':'#abb2bf','cterm':'145','cterm16':'7'}})
syntax enable
let g:indentLine_char='¦' "│
let g:python_highlight_all=1
let g:rainbow_active=1
let g:onedark_hide_endofbuffer=1
let g:lightline={'colorscheme':'onedark'}
let g:vim_json_syntax_conceal=0
let g:vim_markdown_conceal=0
let g:vim_markdown_conceal_code_blocks=0
call plug#begin('~/.vim')
Plug 'sheerun/vim-polyglot'
Plug 'itchyny/lightline.vim'
Plug 'pangloss/vim-javascript'
Plug 'othree/yajs.vim'
Plug 'othree/es.next.syntax.vim'
Plug 'othree/javascript-libraries-syntax.vim'
Plug 'kuangyujing/html5.vim'
Plug 'maxmellon/vim-jsx-pretty'
Plug 'yggdroot/indentline'
Plug 'hdima/python-syntax'
Plug 'Vimjas/vim-python-pep8-indent'
Plug 'joshdick/onedark.vim'
Plug 'luochen1990/rainbow'
call plug#end()
colorscheme onedark
