# PATH
export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# PS1
export PS1='\[\e[2m\]\h:\[\e[0m\]\W\[\e[2m\]$(__git_ps1 " (%s)")\[\e[0m\] \$ '

# bash options
set -o vi
set -o ignoreeof

# bash history
HISTCONTROL=ignoreboth
HISTIGNORE='ls:clear'

# bash bind
bind "TAB:menu-complete"
bind "set show-all-if-ambiguous on"
bind "set completion-ignore-case on"
bind "set menu-complete-display-prefix on"

# bash completion
. /etc/bash_completion
. /etc/bash_completion.d/npm-completion
. /etc/bash_completion.d/git-prompt

# git prompt config
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUPSTREAM=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_STATESEPARATOR=

# aws-cli completion
complete -C /usr/local/bin/aws_completer aws

# aliases
alias r='fc -s'
alias l='ls'
alias sl='ls'
alias la='ls -a'
alias ll='ls -l'
alias ls='ls -h --color=auto'
alias free='free -hw'
alias vmstat='vmstat -w 1'

